<span style="background-color: #0000CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#0000CC" /></span>
<span style="background-color: #0000FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#0000FF BLUE" /></span>
<span style="background-color: #0033CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#0033CC" /></span>
<span style="background-color: #0033FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#0033FF" /></span>
<span style="background-color: #0066FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#0066FF" /></span>
<span style="background-color: #009999; height:20px; width:22px;"><input type="radio" name="kolor" value="#009999" /></span>
<span style="background-color: #0099CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#0099CC" /></span>
<span style="background-color: #0099FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#0099FF" /></span>
<span style="background-color: #00CC33; height:20px; width:22px;"><input type="radio" name="kolor" value="#00CC33" /></span>
<span style="background-color: #00CC66; height:20px; width:22px;"><input type="radio" name="kolor" value="#00CC66" /></span>
<span style="background-color: #00CC99; height:20px; width:22px;"><input type="radio" name="kolor" value="#00CC99" /></span>
<span style="background-color: #00CCCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#00CCCC" /></span>
<span style="background-color: #00CCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#00CCFF" /></span>
<span style="background-color: #00FF00; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FF00 LIME" /></span>
<span style="background-color: #00FF33; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FF33" /></span>
<span style="background-color: #00FF66; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FF66" /></span>
<span style="background-color: #00FF99; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FF99" /></span>
<span style="background-color: #00FFCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FFCC" /></span>
<span style="background-color: #00FFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#00FFFF AQUA" /></span>
<span style="background-color: #3232CD; height:20px; width:22px;"><input type="radio" name="kolor" value="#3232CD" /></span>
<span style="background-color: #3299CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#3299CC" /></span>
<span style="background-color: #32CD32; height:20px; width:22px;"><input type="radio" name="kolor" value="#32CD32" /></span>
<span style="background-color: #32CD99; height:20px; width:22px;"><input type="radio" name="kolor" value="#32CD99" /></span>
<span style="background-color: #3300FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#3300FF" /></span>
<span style="background-color: #3333CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#3333CC" /></span>
<span style="background-color: #3333FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#3333FF" /></span>
<span style="background-color: #336699; height:20px; width:22px;"><input type="radio" name="kolor" value="#336699" /></span>
<span style="background-color: #3366CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#3366CC" /></span>
<span style="background-color: #3366FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#3366FF" /></span>
<span style="background-color: #339900; height:20px; width:22px;"><input type="radio" name="kolor" value="#339900" /></span>
<span style="background-color: #339966; height:20px; width:22px;"><input type="radio" name="kolor" value="#339966" /></span>
<span style="background-color: #339999; height:20px; width:22px;"><input type="radio" name="kolor" value="#339999" /></span>
<span style="background-color: #3399CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#3399CC" /></span>
<span style="background-color: #3399FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#3399FF" /></span>
<span style="background-color: #33CC00; height:20px; width:22px;"><input type="radio" name="kolor" value="#33CC00" /></span>
<span style="background-color: #33CC99; height:20px; width:22px;"><input type="radio" name="kolor" value="#33CC99" /></span>
<span style="background-color: #33CCCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#33CCCC" /></span>
<span style="background-color: #33CCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#33CCFF" /></span>
<span style="background-color: #33FF00; height:20px; width:22px;"><input type="radio" name="kolor" value="#33FF00" /></span>
<span style="background-color: #33FFCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#33FFCC" /></span>
<span style="background-color: #33FFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#33FFFF" /></span>
<span style="background-color: #38B0DE; height:20px; width:22px;"><input type="radio" name="kolor" value="#38B0DE" /></span>
<span style="background-color: #4D4DFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#4D4DFF" /></span>
<span style="background-color: #6600CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#6600CC" /></span>
<span style="background-color: #6600FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#6600FF" /></span>
<span style="background-color: #6633CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#6633CC" /></span>
<span style="background-color: #6633FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#6633FF" /></span>
<span style="background-color: #6666CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#6666CC" /></span>
<span style="background-color: #6666FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#6666FF" /></span>
<span style="background-color: #669900; height:20px; width:22px;"><input type="radio" name="kolor" value="#669900" /></span>
<span style="background-color: #669999; height:20px; width:22px;"><input type="radio" name="kolor" value="#669999" /></span>
<span style="background-color: #6699CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#6699CC" /></span>
<span style="background-color: #6699FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#6699FF" /></span>
<span style="background-color: #66CC00; height:20px; width:22px;"><input type="radio" name="kolor" value="#66CC00" /></span>
<span style="background-color: #66CCCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#66CCCC" /></span>
<span style="background-color: #66CCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#66CCFF" /></span>
<span style="background-color: #66FF00; height:20px; width:22px;"><input type="radio" name="kolor" value="#66FF00" /></span>
<span style="background-color: #66FFCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#66FFCC" /></span>
<span style="background-color: #66FFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#66FFFF" /></span>
<span style="background-color: #7093DB; height:20px; width:22px;"><input type="radio" name="kolor" value="#7093DB" /></span>
<span style="background-color: #70DB93; height:20px; width:22px;"><input type="radio" name="kolor" value="#70DB93" /></span>
<span style="background-color: #717171; height:20px; width:22px;"><input type="radio" name="kolor" value="#717171" /></span>
<span style="background-color: #878787; height:20px; width:22px;"><input type="radio" name="kolor" value="#878787" /></span>
<span style="background-color: #8C7853; height:20px; width:22px;"><input type="radio" name="kolor" value="#8C7853" /></span>
<span style="background-color: #8D8D8D; height:20px; width:22px;"><input type="radio" name="kolor" value="#8D8D8D" /></span>
<span style="background-color: #8F8FBD; height:20px; width:22px;"><input type="radio" name="kolor" value="#8F8FBD" /></span>
<span style="background-color: #8FBC8F; height:20px; width:22px;"><input type="radio" name="kolor" value="#8FBC8F" /></span>
<span style="background-color: #909090; height:20px; width:22px;"><input type="radio" name="kolor" value="#909090" /></span>
<span style="background-color: #9370DB; height:20px; width:22px;"><input type="radio" name="kolor" value="#9370DB" /></span>
<span style="background-color: #939393; height:20px; width:22px;"><input type="radio" name="kolor" value="#939393" /></span>
<span style="background-color: #93DB70; height:20px; width:22px;"><input type="radio" name="kolor" value="#93DB70" /></span>
<span style="background-color: #969696; height:20px; width:22px;"><input type="radio" name="kolor" value="#969696" /></span>
<span style="background-color: #9900CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#9900CC" /></span>
<span style="background-color: #9900FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#9900FF" /></span>
<span style="background-color: #9932CD; height:20px; width:22px;"><input type="radio" name="kolor" value="#9932CD" /></span>
<span style="background-color: #9933CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#9933CC" /></span>
<span style="background-color: #996699; height:20px; width:22px;"><input type="radio" name="kolor" value="#996699" /></span>
<span style="background-color: #9966CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#9966CC" /></span>
<span style="background-color: #9966FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#9966FF" /></span>
<span style="background-color: #999900; height:20px; width:22px;"><input type="radio" name="kolor" value="#999900" /></span>
<span style="background-color: #9999CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#9999CC" /></span>
<span style="background-color: #9999FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#9999FF" /></span>
<span style="background-color: #99CC00; height:20px; width:22px;"><input type="radio" name="kolor" value="#99CC00" /></span>
<span style="background-color: #99CCCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#99CCCC" /></span>
<span style="background-color: #99CCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#99CCFF" /></span>
<span style="background-color: #99FF00; height:20px; width:22px;"><input type="radio" name="kolor" value="#99FF00" /></span>
<span style="background-color: #99FFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#99FFFF" /></span>
<span style="background-color: #9E9E9E; height:20px; width:22px;"><input type="radio" name="kolor" value="#9E9E9E" /></span>
<span style="background-color: #9F9F5F; height:20px; width:22px;"><input type="radio" name="kolor" value="#9F9F5F" /></span>
<span style="background-color: #A1A1A1; height:20px; width:22px;"><input type="radio" name="kolor" value="#A1A1A1" /></span>
<span style="background-color: #ADEAEA; height:20px; width:22px;"><input type="radio" name="kolor" value="#ADEAEA" /></span>
<span style="background-color: #B5A642; height:20px; width:22px;"><input type="radio" name="kolor" value="#B5A642" /></span>
<span style="background-color: #B5B5B5; height:20px; width:22px;"><input type="radio" name="kolor" value="#B5B5B5" /></span>
<span style="background-color: #CC66CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#CC66CC" /></span>
<span style="background-color: #CC66FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#CC66FF" /></span>
<span style="background-color: #CC99CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#CC99CC" /></span>
<span style="background-color: #CC99FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#CC99FF" /></span>
<span style="background-color: #CCCC33; height:20px; width:22px;"><input type="radio" name="kolor" value="#CCCC33" /></span>
<span style="background-color: #CCCC99; height:20px; width:22px;"><input type="radio" name="kolor" value="#CCCC99" /></span>
<span style="background-color: #CCCCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#CCCCFF" /></span>
<span style="background-color: #CCFFCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#CCFFCC" /></span>
<span style="background-color: #CCFFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#CCFFFF" /></span>
<span style="background-color: #EAADEA; height:20px; width:22px;"><input type="radio" name="kolor" value="#EAADEA" /></span>
<span style="background-color: #EAEAAE; height:20px; width:22px;"><input type="radio" name="kolor" value="#EAEAAE" /></span>
<span style="background-color: #EBC79E; height:20px; width:22px;"><input type="radio" name="kolor" value="#EBC79E" /></span>
<span style="background-color: #F5CCB0; height:20px; width:22px;"><input type="radio" name="kolor" value="#F5CCB0" /></span>
<span style="background-color: #F6F6F6; height:20px; width:22px;"><input type="radio" name="kolor" value="#F6F6F6" /></span>
<span style="background-color: #FF0066; height:20px; width:22px;"><input type="radio" name="kolor" value="#FF0066" /></span>
<span style="background-color: #FF0099; height:20px; width:22px;"><input type="radio" name="kolor" value="#FF0099" /></span>
<span style="background-color: #FF00CC; height:20px; width:22px;"><input type="radio" name="kolor" value="#FF00CC" /></span>
<span style="background-color: #FF00FF; height:20px; width:22px;"><input type="radio" name="kolor" value="#FF00FF FUCHSIA" /></span>
<span style="background-color: #FF2400; height:20px; width:22px;"><input type="radio" name="kolor" value="#FF2400" /></span>
<span style="background-color: #FFCC00; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFCC00" /></span>
<span style="background-color: #FFCCCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFCCCC" /></span>
<span style="background-color: #FFCCFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFCCFF" /></span>
<span style="background-color: #FFFF00; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFFF00 YELLOW" /></span>
<span style="background-color: #FFFF33; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFFF33" /></span>
<span style="background-color: #FFFF99; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFFF99" /></span>
<span style="background-color: #FFFFCC; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFFFCC" /></span>
<span style="background-color: #FFFFFF; height:20px; width:22px;"><input type="radio" name="kolor" value="#FFFFFF WHITE" /></span>
